<?php

namespace ContainerN4ELf6T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLuckyChoiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LuckyChoice' shared autowired service.
     *
     * @return \App\Controller\LuckyChoice
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/LuckyChoice.php';

        return $container->services['App\\Controller\\LuckyChoice'] = new \App\Controller\LuckyChoice();
    }
}
