<?php

namespace ContainerN4ELf6T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageTestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PageTest' shared autowired service.
     *
     * @return \App\Controller\PageTest
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/PageTest.php';

        return $container->services['App\\Controller\\PageTest'] = new \App\Controller\PageTest();
    }
}
