<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAEvsSY3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAEvsSY3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAEvsSY3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAEvsSY3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAEvsSY3\App_KernelDevDebugContainer([
    'container.build_hash' => 'AEvsSY3',
    'container.build_id' => '256a8574',
    'container.build_time' => 1775650039,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAEvsSY3');
